nohup: ignoring input
/home/ubuntu/miniforge3/envs/mm/lib/python3.10/site-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "/home/ubuntu/LMH/sr-press/express/datasets.py", line 63, in __init__
    [
  File "/home/ubuntu/LMH/sr-press/express/datasets.py", line 64, in <listcomp>
    pd.read_parquet(self.store / f"x_{xfn.__name__}.parquet")[cols]
  File "/home/ubuntu/miniforge3/envs/mm/lib/python3.10/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
  File "/home/ubuntu/miniforge3/envs/mm/lib/python3.10/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
  File "/home/ubuntu/miniforge3/envs/mm/lib/python3.10/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
  File "/home/ubuntu/miniforge3/envs/mm/lib/python3.10/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/LMH/sr-press/stores/datasets/train/x_closest_11_players.parquet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/LMH/sr-press/train.py", line 95, in <module>
    train_dataset = PressingDataset(
  File "/home/ubuntu/LMH/sr-press/express/datasets.py", line 79, in __init__
    raise FileNotFoundError("No complete dataset found at %s. Run 'create' to create it.", self.store)
FileNotFoundError: [Errno No complete dataset found at %s. Run 'create' to create it.] /home/ubuntu/LMH/sr-press/stores/datasets/train
